services:
  mysql_db:
    image: mysql:8.0
    container_name: appointment_mysql
    restart: always
    environment:
      # Estos valores los toma de tu archivo .env
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: